# Generated by Django 4.2.9 on 2024-07-30 15:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='time',
            field=models.TimeField(default=datetime.time(15, 46, 50, 691527), verbose_name='Во сколько?'),
        ),
    ]
