# Generated by Django 5.0.7 on 2024-07-30 15:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0007_alter_habit_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='time',
            field=models.TimeField(default=datetime.time(15, 57, 31, 244279), verbose_name='Во сколько?'),
        ),
    ]
